name: web-automation-demo
on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.13]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build Docker image
        run: docker build -t web-automation-demo .

      - name: Run tests inside Docker
        run: |
          mkdir -p docs
          docker run --rm \
            -v "${{ github.workspace }}/docs:/docs" \
            web-automation-demo \
            sh -c "pytest --html=/docs/report.html --self-contained-html \
            --json-report --json-report-file=/docs/pytest-report.json"     

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: docs/report.html
      # newman (if you want to run Postman collection in CI)
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install newman
        run: npm install -g newman newman-reporter-html
      - name: Run Postman collection
        run: |          
          newman run data/collection.json \
            -r cli,json,html \
            --reporter-json-export docs/postman-report.json \
            --reporter-html-export docs/postman-report.html
      - name: Upload newman report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: postman-report
          path: docs/

